.github/workflows/manage-surge-deployments.yml
Let us list and teardown deployments by triggering workflow manually.
I have teardown deployments related to closed PR with the workflow.
In the future, this could be improved by periodically running the workflow and make it teardown closed PR (see also https://github.com/bonitasoft/bonita-documentation-site/issues/178)
**Before teardown**
**After teardown**
**Opened PR**
=> Add workflow to manage surge deployments

.github/workflows/teardown-inactive-surge-deployments.yml
We already have a workflow to list deployments and teardown deployments one by one.
This new workflow launched on regular basis or on demand ensures that we don't keep old deployments.
Inspired from https://github.com/bonitasoft/bonita-documentation-site/pull/316
=> [INFRA] Add a GH WF to teardown old surge deployments

.github/release-drafter.yml, .github/workflows/fill-gh-draft-release.yml
Match the bpmn-visualization current configuration
- Collapse dependencies
- Add changelog
- dependabot exclude from contributors (but no dependabot replacers)
Allow to run the GitHub workflow on demand
=> [INFRA] Update the release-drafter configuration

.github/workflows/list-installed-packages-and-tools.yml
Run on a daily basis to help detect environment changes. Logs will help doing diff to detect softwares and tools changes.
Not done on macOS.
based on implementation of https://github.com/tbouffard/playground-release-drafter-and-gh-pages/pull/89covers https://github.com/process-analytics/bpmn-visualization-js/issues/1933
Initially, the purpose of this PR was to check the chrome and edge browser versionsThe first idea that came to me was to open a browser and check the version. That could be done with playwright and take a screenshot of the page and store it as an artifact.For instance, the following urls provide the browser version- chrome://settings/help- brave://settings/help- edge??
Listing softwares and tools with a CLI is less painfulll and provide information for more elements, so so …
=> [INFRA] List packages and tools installed in gh action runners

.github/actions/surge-preview-tools/dist/index.js, .github/actions/surge-preview-tools/src/index.js, .github/workflows/surge-preview-for-pr.yml
Add `https` at the beginning of the output to have a valid url.
=> [FIX] Surge tools action - add protocol in the surge-preview-url output

.github/release-drafter.yml
Avoid forgetting to delete the reminder comments and not updating the full changelog link.
This is what we have done manually in https://github.com/process-analytics/bpmn-visualization-js/releases/tag/v0.26.0
=> [INFRA] Improve full changelog visibility in release notes

.github/release-drafter.yml
Labels changed in the GitHub repository
- infra:refactoring --> refactoring
- infra:build --> chore
- infra:repo: removed
=> [INFRA] Update release-drafter after label changes

.github/dependabot.yml, .github/release-drafter.yml
Dependabot now creates Pull Requests that are not present in the release notes.
The release notes doesn't collapse the dependency updates list.
refs https://github.com/process-analytics/bpmn-visualization-R/issues/104
refs https://github.com/process-analytics/bpmn-visualization-js/issues/2208
=> [DOC] Do not add dev dependencies to release notes

.github/workflows/release-R.yml
Also fix the tags fetch command (missing s)
Covers https://github.com/process-analytics/bpmn-visualization-R/issues/179
`git pull --tags`: https://www.git-scm.com/docs/git-pull#Documentation/git-pull.txt---tags
=> [INFRA] Reduce the number of push during the R release

.github/dependabot.yml, .github/workflows/post-release-update_bpmn_visualization_version_in_Examples_repo.yml, .github/workflows/post-release-update_bpmn_visualization_version_in_R_repo.yml, .github/workflows/pr-metadata-checks.yml, .github/workflows/release-R.yml, .github/workflows/release-bpmn_visualization.yml
Add a dedicated workflow to enforce the rule. It runs on `pull_request_target` to handle PR created by Dependabot and from fork repositories.
Dependabot configuration: change PR title prefix.
Update the GitHub workflows that create commits and PR. They now follow "conventional commits".
=> chore: ensure that the PR title follows "Conventional Commits"

.github/workflows/announce-new-release.yml
It is no longer possible to post a tweet with the API without a paid plan (and we only have a free plan). So, remove the automation.
=> ci: remove job that post Tweet

.github/workflows/release-R.yml, .github/workflows/release-bpmn_visualization.yml
The workflow commits to the main branch and the branch protection configured in the GitHub repository prevents this for all users.
Previously, the protection was temporarily bypassed and the user performing the commit required administrator permissions (due to the configuration of the branch protection).
Now protection is done using GitHub branch ruleset, and there's no need to bypass protection. In this way, workflow can be simplified.
The settings have already been updated
- rulesets replaces branch and tag protection: https://github.com/process-analytics/bpmn-visualization-js/rules (publicly visible)
repository
- permissions of the user performing the Git operations in the repository has been downgraded. ⚠️ **IMPORTANT**: this PR must then be merged prior doing the next release. The …
=> ci(release): eliminate bypassing of branch protection

.github/workflows/delete-artifacts-of-workflow.yml
There is no need to run it in all PR.
=> ci: on run `delete-artifacts-of-workflow` on demand

.github/workflows/surge-build-pr-artifact.yml, .github/workflows/surge-upload.yml, public/docs/index.html
* Adding Paths to  run action only when specific will be updated
* Rename the upload artifact name
=> ci: surge-build uses public docs

.github/workflows/surge-pr-fork-03-teardown.yml
It was using the same name as an existing workflow, so this mess the Actions list and the PR checks execution
=> ci: fix name of the surge preview teardown workflow

.github/dependabot.yml
When a minor version of TypeScript is released, typedoc must be updated as well.
This is because old typedoc versions don't support the new TypeScript version
This is what we already do in https://github.com/process-analytics/bpmn-visualization-js/blob/e13994b2ddd23e7a242d0b781021dc41342faad5/.github/dependabot.yml
=> chore(dependabot): group typescript related dependencies

.github/workflows/surge-pr-fork-02-deploy.yml, .github/workflows/surge-pr-fork-03-teardown.yml
Previously, this wasn't set in `dawidd6/action-download-artifact` so the action was doing a search to retrieve the artifact.
It was using default search parameters, so it skip workflow runs for PR from forks, and always considered the latest run of the workflow.
So, when several PR was opened simultaneously, a wrong artifact could be retrieved.
Covers https://github.com/bonitasoft/bonita-documentation-site/issues/741
=> fix(surge-deploy): get artifact from the specific workflow run

.github/workflows/post-release-simulate-new-version-available-on-npm.yml
There were missing double quotes.
Covers https://github.com/process-analytics/bpmn-visualization-js/issues/2864
=> fix: clean syntax when sending repository_dispatch

.github/workflows/post-release-update_bpmn_visualization_version_in_Examples_repo.yml, .github/workflows/surge-pr-fork-02-deploy.yml
To test process-analytics/bpmn-visualization-examples#614
Tested with [https://github.com/process-analytics/github-actions-playground/actions/runs/12926209301/job/36048741946?pr=399](https://github.com/process-analytics/github-actions-playground/actions/runs/12926209301/job/36048741946?pr=399) and https://github.com/process-analytics/github-actions-playground/actions/runs/12926371059.
=> ci: bump action-download-artifact from v7 to v8

.github/workflows/list-installed-packages-and-tools.yml
Add ubuntu-24.04 and windows-2025
=> feat: list software on more version of GH runners

.github/actions/build-documentation/action.yml
We were previously using Node 16 which is EOL and not supported by Typedoc, so warnings occured.
=> ci: build documentation with Node 22
